services:
  - type: web
    name: vibenest-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://vibenest.onrender.com
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
