export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";

export const ACCESS_CHAT_REQUEST = "ACCESS_CHAT_REQUEST";
export const ACCESS_CHAT_SUCCESS = "ACCESS_CHAT_SUCCESS";
export const ACCESS_CHAT_FAIL = "ACCESS_CHAT_FAIL";

export const CLEAR_CHAT_STATE = "CLEAR_CHAT_STATE";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const CLEAR_SELECTED_CHAT = "CLEAR_SELECTED_CHAT";
export const SET_CHATS = "SET_CHATS";

//messages

export const SELECTED_CHAT = "SELECTED_CHAT";
export const SET_MESSAGES = "SET_MESSAGES";
export const LOADING_MESSAGES = "LOADING_MESSAGES";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const SET_TYPING = "SET_TYPING";
export const SET_SOCKET_CONNECTED = "SET_SOCKET_CONNECTED";
export const SET_IS_TYPING = "SET_IS_TYPING";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_FETCH_AGAIN = "SET_FETCH_AGAIN";
export const SET_NEW_MESSAGE = "SET_NEW_MESSAGE";
export const ADD_MESSAGE = "ADD_MESSAGE";
