export const STORY_LIST_REQUEST = "STORY_LIST_REQUEST";
export const STORY_LIST_SUCCESS = "STORY_LIST_SUCCESS";
export const STORY_LIST_FAIL = "STORY_LIST_FAIL";

export const STORY_UPLOAD_REQUEST = "STORY_UPLOAD_REQUEST";
export const STORY_UPLOAD_SUCCESS = "STORY_UPLOAD_SUCCESS";
export const STORY_UPLOAD_FAIL = "STORY_UPLOAD_FAIL";
export const STORY_UPLOAD_RESET = "STORY_UPLOAD_RESET";

export const STORY_SEEN_REQUEST = "STORY_SEEN_REQUEST";
export const STORY_SEEN_SUCCESS = "STORY_SEEN_SUCCESS";
export const STORY_SEEN_FAIL = "STORY_SEEN_FAIL";

export const STORY_DELETE_REQUEST = "STORY_DELETE_REQUEST";
export const STORY_DELETE_SUCCESS = "STORY_DELETE_SUCCESS";
export const STORY_DELETE_FAIL = "STORY_DELETE_FAIL";
